version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    # ports:
    #   - "6379:6379"

  clockin_bot:
    build: ./clockin
    container_name: bot1_container
    env_file:
      - /home/gitlab-runner/envs/clockin.env
